extends: conditional
message: "Don't use a slash mark (/) to present a choice among, or a series of, actions or objects ('%s'). Rewrite the phrase to eliminate the slash mark."
link: 'https://github.com/rackerlabs/docs-style-guide/blob/master/style-guide/style/punctuation.rst'
level: suggestion
ignorecase: true
first: '(\s|^)\w+/\w+(\s)'
second: '(\s|^)\w+/\w+(\s)'
exceptions:
 - and/or
